[package]
name = "rasm"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = true
opt-level = 0

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
